name: Fly Deploy Backend
on:
  push:
    tags:
      - 'backend-*'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
        #   fetch-depth: 0
    #   - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx build backend
  deploy:
    needs: main
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: fly deploy --dockerfile ./packages/backend/Dockerfile --config ./packages/backend/fly.toml --remote-only --detach
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}