name: Fly Deploy Backend
on:
  push:
    tags:
      - 'backend-*'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
        #   fetch-depth: 0
    #   - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx build backend
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --detach --dockerfile ./packages/backend/Dockerfile --config ./packages/backend/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}