name: Build & Deploy
on:
  push:
    tags:
      - 'worker-*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            mkdir app 
            cd app 
            git clone https://thedeveloper.network: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@github.com/thedeveloper-network/immobilier.git .
            cd packages/op-worker
            npm install
            echo "npm packages installed"
            npm run build
            npm start
            echo 'Deployment successful to digital ocean' 