name: Build & Deploy
on:
  push:
    tags:
      - 'worker-*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npx nx build op-worker

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/packages/op-worker
  server-clean:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Server
        uses: appleboy/ssh-action@v0.1.3
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_USER: ${{ secrets.REDIS_USER }}
          REDIS_PASS: ${{ secrets.REDIS_PASS }}
        with:
          host: ${{secrets.DO_SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.DO_SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.DO_SSH_USERNAME }} # User of the server you want to ssh into
          envs: REDIS_HOST,REDIS_PORT,REDIS_USER,REDIS_PASS
          script: |
            sudo pm2 kill
            rm -rf app
            mkdir app
            # cd app 
            # echo "tag ${{ github.ref_name }}"
            # git clone --branch ${{ github.ref_name }} https://thedeveloper.network:${{ secrets.GITHUB_TOKEN }}@github.com/thedeveloper-network/immobilier.git .
            # # cd packages/op-worker
            # npm ci
            # echo "npm packages installed"
            # export REDIS_HOST="${{ secrets.REDIS_HOST }}"
            # export REDIS_PORT="${{ secrets.REDIS_PORT }}"
            # export REDIS_USER="${{ secrets.REDIS_USER }}"
            # export REDIS_PASS="${{ secrets.REDIS_PASS }}"
            # npx nx build op-worker
            # sudo pm2 start dist/packages/op-worker/src/index.js
            # echo 'Deployment successful to digital ocean' 
  deploy:
    runs-on: ubuntu-latest
    needs: [build,server-clean]
    steps:
        - name: Download Build
          uses: actions/download-artifact@v2
          with:
            name: build
            path: dist
        - name: Deploy to DO
          uses: appleboy/scp-action@v0.1.4
          with:
            host: ${{ secrets.DO_SSH_HOST }}
            username: ${{ secrets.DO_SSH_USERNAME }}
            key: ${{ secrets.DO_SSH_KEY }}
            source: "dist/*"
            target: ~/app
